# Generated by Django 5.2.4 on 2025-12-27 19:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_photo_publishing'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=512, unique=True)),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration Persistent Storage',
                'verbose_name_plural': 'Integration Persistent Storage',
            },
        ),
        migrations.CreateModel(
            name='PythonPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nickname', models.CharField(blank=True, help_text='Optional', max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('module', models.CharField(help_text='Python module name (without .py extension)', max_length=255)),
                ('config', models.JSONField(blank=True, default=dict, help_text='JSON object containing plugin configuration with environment variable support', null=True)),
            ],
            options={
                'verbose_name': 'Python Plugin',
            },
        ),
        migrations.CreateModel(
            name='RunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_uuid', models.UUIDField(db_index=True, null=True)),
                ('start_timestamp', models.DateTimeField(blank=True, null=True)),
                ('end_timestamp', models.DateTimeField(blank=True, null=True)),
                ('caller', models.CharField(choices=[('MANUAL', 'Manual'), ('EVENT_SCHEDULER', 'Event Scheduler')], max_length=32)),
                ('successful', models.BooleanField(default=False)),
                ('run_log', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WebRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nickname', models.CharField(blank=True, help_text='Optional', max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], max_length=32)),
                ('url', models.URLField()),
                ('headers', models.TextField(blank=True, default='', help_text='One per line in the format Header: Value', null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Web Request',
            },
        ),
        migrations.CreateModel(
            name='PluginEntityParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_uuid', models.UUIDField(db_index=True, help_text='UUID of the entity')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='JSON object containing entity-specific parameters', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_parameters', to='integration.pythonplugin')),
            ],
            options={
                'verbose_name': 'Plugin Entity Parameters',
                'verbose_name_plural': 'Plugin Entity Parameters',
                'unique_together': {('plugin', 'entity_uuid')},
            },
        ),
        migrations.CreateModel(
            name='PhotoPluginExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_exclusions', to='core.photo')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_exclusions', to='integration.pythonplugin')),
            ],
            options={
                'verbose_name': 'Photo Plugin Exclusion',
                'verbose_name_plural': 'Photo Plugin Exclusions',
                'unique_together': {('photo', 'plugin')},
            },
        ),
    ]
