# Generated by Django 5.2.4 on 2025-12-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webrequest',
            name='headers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
