# Generated by Django 6.0.4 on 2026-09-25 14:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


def copy_python_plugins(apps, schema_editor):
    PythonPlugin = apps.get_model("integration", "PythonPlugin")
    IntegrationPlugin = apps.get_model("integration", "IntegrationPlugin")

    for plugin in PythonPlugin.objects.all().iterator():
        IntegrationPlugin.objects.create(
            uuid=plugin.uuid,
            nickname=plugin.nickname,
            active=plugin.active,
            module=plugin.module,
            config=plugin.config,
            channel=None,
        )


def parse_headers(headers):
    parsed_headers = {}
    for line in (headers or "").splitlines():
        if not line.strip() or ":" not in line:
            continue
        key, value = line.split(":", 1)
        parsed_headers[key.strip()] = value.strip()
    return parsed_headers


def convert_web_requests(apps, schema_editor):
    WebRequest = apps.get_model("integration", "WebRequest")
    IntegrationPlugin = apps.get_model("integration", "IntegrationPlugin")

    for web_request in WebRequest.objects.all().iterator():
        IntegrationPlugin.objects.create(
            uuid=web_request.uuid,
            nickname=web_request.nickname,
            active=web_request.active,
            module="webrequest",
            config={
                "url": web_request.url,
                "method": web_request.method,
                "headers": parse_headers(web_request.headers),
                "body": web_request.body or "",
            },
            channel=None,
        )


def delete_web_request_run_results(apps, schema_editor):
    WebRequest = apps.get_model("integration", "WebRequest")
    RunResult = apps.get_model("integration", "RunResult")

    web_request_uuids = WebRequest.objects.values_list("uuid", flat=True)
    RunResult.objects.filter(integration_uuid__in=web_request_uuids).delete()


def copy_run_result_integrations(apps, schema_editor):
    IntegrationPlugin = apps.get_model("integration", "IntegrationPlugin")
    RunResult = apps.get_model("integration", "RunResult")

    plugin_ids_by_uuid = dict(
        IntegrationPlugin.objects.values_list("uuid", "id")
    )
    for run_result in RunResult.objects.exclude(integration_uuid__isnull=True).iterator():
        integration_plugin_id = plugin_ids_by_uuid.get(run_result.integration_uuid)
        if integration_plugin_id is not None:
            run_result.integration_plugin_id = integration_plugin_id
            run_result.save(update_fields=["integration_plugin"])


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_alter_photopluginexclusion_photo'),
        ('media', '0002_channels'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nickname', models.CharField(blank=True, help_text='Optional', max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('module', models.CharField(help_text='Python module name (without .py extension)', max_length=255)),
                ('config', models.JSONField(blank=True, default=dict, help_text='JSON object containing plugin configuration with environment variable support', null=True)),
                ('channel', models.ForeignKey(blank=True, help_text='Subscribe to a photo publication channel.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.channel')),
            ],
            options={
                'verbose_name': 'Integration Plugin',
            },
        ),
        migrations.RunPython(copy_python_plugins, migrations.RunPython.noop),
        migrations.RunPython(convert_web_requests, migrations.RunPython.noop),
        migrations.RunPython(delete_web_request_run_results, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='WebRequest',
        ),
        migrations.AlterUniqueTogether(
            name='photopluginexclusion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='photopluginexclusion',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='photopluginexclusion',
            name='plugin',
        ),
        migrations.AlterUniqueTogether(
            name='pluginentityparameters',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pluginentityparameters',
            name='plugin',
        ),
        migrations.AddField(
            model_name='runresult',
            name='integration_plugin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_results', to='integration.integrationplugin'),
        ),
        migrations.RunPython(copy_run_result_integrations, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='runresult',
            name='integration_uuid',
        ),
        migrations.DeleteModel(
            name='PhotoPluginExclusion',
        ),
        migrations.DeleteModel(
            name='PluginEntityParameters',
        ),
        migrations.DeleteModel(
            name='PythonPlugin',
        ),
    ]
