# Generated by Django 5.2.4 on 2025-12-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_alter_webrequest_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webrequest',
            name='headers',
            field=models.TextField(blank=True, default='', help_text='One per line in the format Header: Value', null=True),
        ),
    ]
