# Generated by Django 5.2.4 on 2025-12-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_alter_webrequest_headers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webrequest',
            options={'verbose_name': 'Web Request'},
        ),
        migrations.RenameField(
            model_name='integrationrunresult',
            old_name='response',
            new_name='run_log',
        ),
        migrations.AddField(
            model_name='integrationrunresult',
            name='caller',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('EVENT_SCHEDULER', 'Event Scheduler')], default='MANUAL', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integrationrunresult',
            name='integration_object',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
