# Generated by Django 5.2.4 on 2025-12-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0005_alter_webrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationrunresult',
            name='successful',
            field=models.BooleanField(default=False),
        ),
    ]
