# Generated by Django 5.2.4 on 2025-12-11 22:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0006_alter_integrationrunresult_successful'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationrunresult',
            options={'ordering': ['-start_timestamp']},
        ),
        migrations.RemoveField(
            model_name='integrationrunresult',
            name='integration_object',
        ),
        migrations.RemoveField(
            model_name='integrationrunresult',
            name='integration_type',
        ),
        migrations.AddField(
            model_name='integrationrunresult',
            name='integration_uuid',
            field=models.UUIDField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='webrequest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
