# Generated by Django 5.2.4 on 2025-12-19 16:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0007_alter_integrationrunresult_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('nickname', models.CharField(blank=True, help_text='Optional', max_length=255, null=True)),
                ('module', models.CharField(help_text='Python module name (without .py extension)', max_length=255, unique=True)),
                ('global_events', models.BooleanField(default=False, help_text='Receive on_global_change events')),
                ('config', models.TextField(blank=True, default='', help_text='One per line in the format key: value (JSON will be sent to plugin)', null=True)),
            ],
            options={
                'verbose_name': 'Python Plugin',
            },
        ),
    ]
