# Generated by Django 5.2.4 on 2025-12-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0008_pythonplugin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pythonplugin',
            name='global_events',
        ),
        migrations.AddField(
            model_name='pythonplugin',
            name='receive_global_events',
            field=models.BooleanField(db_column='global', default=False, help_text='Receive on_global_change events'),
        ),
    ]
