# Generated by Django 5.2.4 on 2025-12-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0009_remove_pythonplugin_global_events_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=512, unique=True)),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration Persistent Storage',
                'verbose_name_plural': 'Integration Persistent Storage',
            },
        ),
        migrations.AlterField(
            model_name='pythonplugin',
            name='config',
            field=models.TextField(blank=True, default='', help_text='One per line in the format key: value (JSON parsed with ENV vars)', null=True),
        ),
        migrations.AlterField(
            model_name='pythonplugin',
            name='receive_global_events',
            field=models.BooleanField(default=False, help_text='Receive global changed events'),
        ),
    ]
