# Generated by Django 5.2.4 on 2025-12-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0010_integrationpersistentstorage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pythonplugin',
            name='receive_global_events',
        ),
    ]
