# Generated by Django 5.2.4 on 2025-12-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0011_remove_pythonplugin_receive_global_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonplugin',
            name='module',
            field=models.CharField(help_text='Python module name (without .py extension)', max_length=255),
        ),
    ]
