# Generated by Django 5.2.4 on 2025-12-24 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_photo_publishing'),
        ('integration', '0012_alter_pythonplugin_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoPluginExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_exclusions', to='core.photo')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_exclusions', to='integration.pythonplugin')),
            ],
            options={
                'verbose_name': 'Photo Plugin Exclusion',
                'verbose_name_plural': 'Photo Plugin Exclusions',
                'unique_together': {('photo', 'plugin')},
            },
        ),
    ]
