# Generated by Django 5.2.4 on 2025-12-26 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0013_photopluginexclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginEntityParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_uuid', models.UUIDField(db_index=True, help_text='UUID of the entity (e.g., Photo)')),
                ('parameters', models.TextField(blank=True, default='', help_text='One per line in the format key: value (JSON parsed with ENV vars)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_parameters', to='integration.pythonplugin')),
            ],
            options={
                'verbose_name': 'Plugin Entity Parameters',
                'verbose_name_plural': 'Plugin Entity Parameters',
                'unique_together': {('plugin', 'entity_uuid')},
            },
        ),
    ]
