services:
  database:
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "4545:5432" # for inspecting in internal applications
    volumes:
      - db:/var/lib/postgresql
  
  redis:
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  db: {}
  redis: {}
