services:
  database:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "4545:5432" # for inspecting in internal applications
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: {}
