# Generated by Django 5.2.4 on 2025-08-06 23:58

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=4096)),
                ('sort_method', models.CharField(choices=[('CREATED', 'Created/Taken'), ('PUBLISHED', 'Published/Uploaded'), ('MANUAL', 'Manual'), ('RANDOM', 'Random')], default='MANUAL', max_length=10)),
                ('sort_ascending', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=4096)),
                ('raw_image', models.ImageField(upload_to=core.models.Photo.get_raw_photo_upload_path)),
                ('publish_date', models.DateTimeField(auto_now=True)),
                ('capture_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoInAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.album')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.photo')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('album', 'photo')},
            },
        ),
        migrations.AddField(
            model_name='album',
            name='_photos',
            field=models.ManyToManyField(related_name='albums', through='core.PhotoInAlbum', to='core.photo'),
        ),
    ]
