# Generated by Django 5.2.4 on 2025-08-19 23:33

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models
from core import UI_THUMBNAIL_SIZE


def create_builtin_sizes(apps, schema_editor):
    Size = apps.get_model('core', 'Size')
    Size.objects.create(
        slug='original',
        comment="Original, unprocessed image",
        max_dimension=2147483647,
        square_crop=False,
        builtin=True,
        can_edit=False,
    )

    Size.objects.create(
        slug=UI_THUMBNAIL_SIZE,
        comment="Photoserv UI thumbnail size",
        max_dimension=256,
        square_crop=False,
        builtin=True,
        can_edit=True,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=4096)),
                ('sort_method', models.CharField(choices=[('CREATED', 'Created/Taken'), ('PUBLISHED', 'Published/Uploaded'), ('MANUAL', 'Manual'), ('RANDOM', 'Random')], default='PUBLISHED', max_length=10)),
                ('sort_descending', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=4096)),
                ('raw_image', models.ImageField(upload_to=core.models.Photo.get_image_file_path)),
                ('publish_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=32, unique=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('max_dimension', models.PositiveIntegerField()),
                ('square_crop', models.BooleanField(default=False)),
                ('builtin', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['max_dimension'],
            },
        ),
        migrations.CreateModel(
            name='PhotoExif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exif', to='core.photo')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoInAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.album')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.photo')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('album', 'photo')},
            },
        ),
        migrations.AddField(
            model_name='album',
            name='_photos',
            field=models.ManyToManyField(related_name='albums', through='core.PhotoInAlbum', to='core.photo', verbose_name='Photos'),
        ),
        migrations.CreateModel(
            name='PhotoSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=core.models.PhotoSize.get_image_file_path)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='core.photo')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.size')),
            ],
            options={
                'unique_together': {('photo', 'size')},
            },
        ),
        migrations.RunPython(create_builtin_sizes),
    ]
