# Generated by Django 5.2.4 on 2025-09-26 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.album'),
        ),
        migrations.AddField(
            model_name='photo',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hide from public API'),
        ),
    ]
