# Generated by Django 5.2.4 on 2025-09-19 17:53

from django.db import migrations, models


def set_old_photos_ready(apps, schema_editor):
    Photo = apps.get_model('core', 'Photo')
    Photo.objects.all().update(ready=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='ready',
            field=models.BooleanField(db_index=True, default=False),
        ),

        migrations.RunPython(set_old_photos_ready),
    ]
