# Generated by Django 5.2.4 on 2025-08-22 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photosize',
            options={'ordering': ['size__max_dimension']},
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, default='', max_length=4096),
        ),
        migrations.CreateModel(
            name='PhotoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField(max_length=128)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.photo')),
            ],
            options={
                'unique_together': {('photo', 'tag')},
            },
        ),
    ]
