# Generated by Django 5.2.4 on 2025-11-05 00:00

import uuid
from django.db import migrations, models


def gen_uuid(apps, schema_editor, model_name):
    Model = apps.get_model('core', model_name)
    for instance in Model.objects.all():
        instance.uuid = uuid.uuid4()
        instance.save()


def generate_uuids(apps, schema_editor):
    for model_name in ['PhotoMetadata', 'Size']:
        gen_uuid(apps, schema_editor, model_name)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_album_parent_photo_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='album',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photometadata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='photometadata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='photometadata',
            name='uuid',
            field=models.UUIDField(db_index=False, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='size',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='size',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='size',
            name='uuid',
            field=models.UUIDField(db_index=False, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),

        migrations.RunPython(generate_uuids, reverse_code=migrations.RunPython.noop, hints={"model_names": ["PhotoMetadata", "Size"]}),

        migrations.AlterField(
            model_name='size',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='photometadata',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
