# Generated by Django 5.2.4 on 2025-08-22 18:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_alter_phototag_options_alter_phototag_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='uuid',
        ),
        migrations.AddField(
            model_name='tag',
            name='public_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
