# Generated by Django 5.2.4 on 2025-12-13 00:48

from django.db import migrations, models
from django.utils import timezone
import django.utils.timezone


def set_published_default(apps, schema_editor):
    Photo = apps.get_model('core', 'Photo')
    now = timezone.now()
    for photo in Photo.objects.all():
        photo._published = not photo.hidden and (photo.publish_date <= now)
        photo.save(update_fields=['_published'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_core_entity_common_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='_published',
            field=models.BooleanField(db_column='published', default=False, null=True),
        ),
        migrations.RunPython(set_published_default, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='photo',
            name='_published',
            field=models.BooleanField(db_column='published', default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='album',
            name='sort_method',
            field=models.CharField(choices=[('CREATED', 'Photo Created Date (Exif)'), ('PUBLISHED', 'Publish Date'), ('MANUAL', 'Manual'), ('RANDOM', 'Random')], default='PUBLISHED', max_length=10),
        ),
    ]
