# Generated by Django 5.2.4 on 2025-08-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_phototag_photo_alter_phototag_tag_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
