# Generated by Django 5.2.4 on 2025-08-24 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capture_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('camera_make', models.CharField(blank=True, default='', max_length=255)),
                ('camera_model', models.CharField(blank=True, default='', max_length=255)),
                ('lens_model', models.CharField(blank=True, default='', max_length=255)),
                ('focal_length', models.FloatField(blank=True, null=True)),
                ('focal_length_35mm', models.FloatField(blank=True, null=True)),
                ('aperture', models.FloatField(blank=True, null=True)),
                ('shutter_speed', models.CharField(blank=True, default='', max_length=64)),
                ('iso', models.PositiveIntegerField(blank=True, null=True)),
                ('copyright', models.CharField(blank=True, default='', max_length=512)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='core.photo')),
            ],
        ),
        migrations.DeleteModel(
            name='PhotoExif',
        ),
    ]
