# Generated by Django 5.2.4 on 2025-08-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_photometadata_delete_photoexif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photometadata',
            name='camera_make',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photometadata',
            name='camera_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photometadata',
            name='capture_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photometadata',
            name='copyright',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='photometadata',
            name='lens_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photometadata',
            name='shutter_speed',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
