# Generated by Django 5.2.4 on 2025-08-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_photometadata_camera_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photometadata',
            name='shutter_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
