# Generated by Django 5.2.4 on 2025-08-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_photometadata_shutter_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='photometadata',
            name='exposure_compensation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photometadata',
            name='exposure_program',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photometadata',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
