# Generated by Django 5.2.4 on 2025-08-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_photometadata_exposure_compensation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photometadata',
            name='flash_did_fire',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
