# Generated by Django 6.0.4 on 2026-09-30 19:23

from django.contrib.auth import get_user_model
from django.db import migrations


def make_existing_active_users_superusers(apps, schema_editor):
    User = get_user_model()
    User.objects.filter(is_active=True).update(is_superuser=True)


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(make_existing_active_users_superusers),
    ]
