CONTENT_BASE_PATH = "content"
CONTENT_RAW_PHOTOS_PATH = f"{CONTENT_BASE_PATH}/raw_photos"
CONTENT_RESIZED_PHOTOS_PATH = f"{CONTENT_BASE_PATH}/processed_photos"

UI_THUMBNAIL_SIZE = "photoserv_ui_thumbnail"
