# Generated by Django 6.0.4 on 2026-09-28 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_existing_keys_to_default_user(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    APIKey = apps.get_model("api_key", "APIKey")
    keys_without_users = APIKey.objects.filter(user__isnull=True)
    if not keys_without_users.exists():
        return

    user = (
        User.objects.filter(is_active=True, is_superuser=True)
        .order_by("pk")
        .first()
    ) or User.objects.filter(is_active=True).order_by("pk").first()
    if user is None:
        raise RuntimeError(
            "Cannot assign API keys: no active user is available."
        )

    keys_without_users.update(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('api_key', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name': 'API Key'},
        ),
        migrations.AddField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='api_keys',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(
            assign_existing_keys_to_default_user,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='apikey',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='api_keys',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
